main:
  name: rest-test
  logger: zerolog
  registry_type: github

post_generate: []

git:
  repo: git@github.com:test/rest-test.git
  module_path: github.com/test/rest-test

tools:
  protobuf_version: 1.7.0
  golang_version: "1.24"
  ogen_version: v1.8.1
  golangci_version: 1.64.8

rest:
  - name: api
    path:
      - ./api.swagger.yml
    api_prefix: /
    version: "v1"
    port: 8080
    generator_type: ogen
    generator_params:
      auth_handler: "off"
  - name: sys
    port: 8085
    version: "v1"
    generator_type: template
    generator_template: sys

applications:
  - name: apiServer
    transport:
      - api
      - sys
