site_name: Onvi Backend Documentation
doc_dir: docs
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mermaid2:

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format