package templater

import (
	"testing"

	"github.com/stretchr/testify/require"
)

type splitDisclamerTestData struct {
	name     string
	content  string
	start    string
	finish   string
	genCode  string
	userCode string
	wantErr  bool
}

func TestSplitDisclaimer1(t *testing.T) {
	testData := []splitDisclamerTestData{
		{
			name: "test1",

			content: `// Code generated by projectStarter generator. DO NOT EDIT. 
// This code was generated from a template. 
//  
// Manual changes to this file may cause unexpected behavior in your application. 
// Manual changes to this file will be overwritten if the code is regenerated. 
//  
// Generate info:  
package main // import package

// This file is intentionally empty to force early versions of Go
// to test compilation for tests.

// Code generated by projectStarter generator. DO NOT EDIT file before this message. 
// Generate info:  
//  
// If you need you can add your code after this message `,
			start: `// Code generated by projectStarter generator. DO NOT EDIT. 
// This code was generated from a template. 
//  
// Manual changes to this file may cause unexpected behavior in your application. 
// Manual changes to this file will be overwritten if the code is regenerated. 
//  
// Generate info:  `,
			finish: `// This file is intentionally empty to force early versions of Go
// to test compilation for tests.

// Code generated by projectStarter generator. DO NOT EDIT file before this message. 
// Generate info:  
//  
// If you need you can add your code after this message `,
			genCode: `package main // import package
`,
			userCode: "",
			wantErr:  false,
		},
		{
			name: "test2",

			content: `# Code generated by projectStarter generator. DO NOT EDIT. 
# This code was generated from a template. 
#  
# Manual changes to this file may cause unexpected behavior in your application. 
# Manual changes to this file will be overwritten if the code is regenerated. 
#  
# Generate info:  
name: CI Pipeline

on:
  push:
    branches:
      - main
      - staging

# Code generated by projectStarter generator. DO NOT EDIT file before this message. 
# Generate info:  
#  
# If you need you can add your code after this message `,
			start: `# Code generated by projectStarter generator. DO NOT EDIT. 
# This code was generated from a template. 
#  
# Manual changes to this file may cause unexpected behavior in your application. 
# Manual changes to this file will be overwritten if the code is regenerated. 
#  
# Generate info:  `,
			finish: `# Code generated by projectStarter generator. DO NOT EDIT file before this message. 
# Generate info:  
#  
# If you need you can add your code after this message `,
			genCode: `name: CI Pipeline

on:
  push:
    branches:
      - main
      - staging
`,
			userCode: "",
			wantErr:  false},
		// {},
		// {},
	}

	for _, d := range testData {
		t.Run(d.name, func(t *testing.T) {
			generatedCode, userData, err := splitDisclaimer(d.content, d.start, d.finish)
			if !d.wantErr && err != nil {
				t.Fatalf("test not expected err but got %s", err)
			}

			if d.wantErr && err == nil {
				t.Fatalf("test expected err but got nil")
			}

			require.Equal(t, d.userCode, userData, "Invalid userData")
			require.Equal(t, d.genCode, generatedCode, "Invalid generatedCode")
		})
	}
}

func TestSplitDisclaimer4(t *testing.T) {

	testFileContent := `// Code generated by projectStarter generator. DO NOT EDIT. 
// This code was generated from a template. 
//  
// Manual changes to this file may cause unexpected behavior in your application. 
// Manual changes to this file will be overwritten if the code is regenerated. 
//  
// Generate info:  
package main // import package

// This file is intentionally empty to force early versions of Go
// to test compilation for tests.

// Code generated by projectStarter generator. DO NOT EDIT file before this message. 
// Generate info:  
//  
// If you need you can add your code after this message `

	testDisclaimerStart := `// Code generated by projectStarter generator. DO NOT EDIT. 
// This code was generated from a template. 
//  
// Manual changes to this file may cause unexpected behavior in your application. 
// Manual changes to this file will be overwritten if the code is regenerated. 
//  
// Generate info:  `

	testDisclaimerFinish := `// This file is intentionally empty to force early versions of Go
// to test compilation for tests.

// Code generated by projectStarter generator. DO NOT EDIT file before this message. 
// Generate info:  
//  
// If you need you can add your code after this message `

	// t.Run("Is there a code before the disclaimer?",  f func(t *testing.T))

	generatedCode, userData, err := splitDisclaimer(testFileContent, testDisclaimerStart, testDisclaimerFinish)
	if err != nil {
		t.Fatalf("there is a code before the disclaimer: %v", err)
		// t.Logf("Project created in %s: %s", generatedCode, userData)
		// t.Errorf()
	}
	t.Logf(" - Code generated by the utility: %s  - User written code: %s", generatedCode, userData)
}

func TestSplitDisclaimer5(t *testing.T) {

	testFileContent := `# Code generated by projectStarter generator. DO NOT EDIT. 
# This code was generated from a template. 
#  
# Manual changes to this file may cause unexpected behavior in your application. 
# Manual changes to this file will be overwritten if the code is regenerated. 
#  
# Generate info:  
name: CI Pipeline

on:
  push:
    branches:
      - main
      - staging

# Code generated by projectStarter generator. DO NOT EDIT file before this message. 
# Generate info:  
#  
# If you need you can add your code after this message `

	testDisclaimerStart := `# Code generated by projectStarter generator. DO NOT EDIT. 
# This code was generated from a template. 
#  
# Manual changes to this file may cause unexpected behavior in your application. 
# Manual changes to this file will be overwritten if the code is regenerated. 
#  
# Generate info:  `

	testDisclaimerFinish := `# Code generated by projectStarter generator. DO NOT EDIT file before this message. 
# Generate info:  
#  
# If you need you can add your code after this message `

	// t.Run("Is there a code before the disclaimer?",  f func(t *testing.T))

	generatedCode, userData, err := splitDisclaimer(testFileContent, testDisclaimerStart, testDisclaimerFinish)
	if err != nil {
		t.Fatalf("there is a code before the disclaimer: %v", err)
		// t.Logf("Project created in %s: %s", generatedCode, userData)
		// t.Errorf()
	}
	t.Logf(" - Code generated by the utility: %s  - User written code: %s", generatedCode, userData)
}

/*
func TestSplitDisclaimer6(t *testing.T) {

	testFileContent := `Code generated by projectStarter generator. DO NOT EDIT.
This code was generated from a template.

Manual changes to this file may cause unexpected behavior in your application.
Manual changes to this file will be overwritten if the code is regenerated.

Generate info: {{ .AppInfo }}

Code generated by projectStarter generator. DO NOT EDIT file before this message.
Generate info: {{ .AppInfo }}

And everything works fine.

If you need you can add your code after this message`

	testDisclaimerStart := `Code generated by projectStarter generator. DO NOT EDIT.
This code was generated from a template.

Manual changes to this file may cause unexpected behavior in your application.
Manual changes to this file will be overwritten if the code is regenerated.

Generate info: {{ .AppInfo }}`

	testDisclaimerFinish := `Code generated by projectStarter generator. DO NOT EDIT file before this message.
Generate info: {{ .AppInfo }}

And everything works fine.

If you need you can add your code after this message`

	// t.Run("Is there a code before the disclaimer?",  f func(t *testing.T))

	generatedCode, userData, err := splitDisclaimer(testFileContent, testDisclaimerStart, testDisclaimerFinish)
	if err == nil {
		t.Fatalf("there is a code before the disclaimer: %v", err)
		// t.Logf("Project created in %s: %s", generatedCode, userData)
		// t.Errorf()
	}
	t.Logf(" - Code generated by the utility: %s  - User written code: %s", generatedCode, userData)
}


func TestSplitDisclaimer2(t *testing.T) {

	testFileContent := `Code generated by projectStarter generator. DO NOT EDIT.
This code was generated from a template.

Manual changes to this file may cause unexpected behavior in your application.
Manual changes to this file will be overwritten if the code is regenerated.

Generate info: {{ .AppInfo }}

Code generated by projectStarter generator. DO NOT EDIT file before this message.
Generate info: {{ .AppInfo }}

And everything works fine.

If you need you can add your code after this message

The code that the user wrote after the disclaimer.`

	testDisclaimerStart := ""

	testDisclaimerFinish := ""

	// t.Run("The old version does not have disclaimers.", SplitDisclaimer(testFileContent, testDisclaimerStart, testDisclaimerFinish))
	t.Run("The old version does not have disclaimers.", func(t *testing.T) {

		generatedCode, userData, err := splitDisclaimer(testFileContent, testDisclaimerStart, testDisclaimerFinish)
		if err != nil {
			t.Fatalf("The old version does not have disclaimers.: %v", err)
			// t.Logf("Project created in %s: %s", generatedCode, userData)
			// t.Errorf()
		}
		t.Logf(" - Code generated by the utility: %s  - User written code: %s", generatedCode, userData)
	})
}

func TestSplitDisclaimer3(t *testing.T) {

	testFileContent := `The code that the user wrote before the disclaimer.

Code generated by projectStarter generator. DO NOT EDIT.
This code was generated from a template.

Manual changes to this file may cause unexpected behavior in your application.
Manual changes to this file will be overwritten if the code is regenerated.

Generate info: {{ .AppInfo }}

Code generated by projectStarter generator. DO NOT EDIT file before this message.
Generate info: {{ .AppInfo }}

And everything works fine.

If you need you can add your code after this message

The code that the user wrote after the disclaimer.`

	testDisclaimerStart := `Code generated by projectStarter generator. DO NOT EDIT.
This code was generated from a template.

Manual changes to this file may cause unexpected behavior in your application.
Manual changes to this file will be overwritten if the code is regenerated.

Generate info: {{ .AppInfo }}`

	testDisclaimerFinish := `Code generated by projectStarter generator. DO NOT EDIT file before this message.
Generate info: {{ .AppInfo }}

And everything works fine.

If you need you can add your code after this message`

	t.Run("Is there a code before the disclaimer?", func(t *testing.T) {
		generatedCode, userData, err := splitDisclaimer(testFileContent, testDisclaimerStart, testDisclaimerFinish)
		if err != nil {
			t.Fatalf("there is a code before the disclaimer: %v", err)
			// t.Logf("Project created in %s: %s", generatedCode, userData)
			// t.Errorf()

		}
		t.Logf(" - Code generated by the utility: %s  - User written code: %s", generatedCode, userData)

	})

}

`Code generated by projectStarter generator. DO NOT EDIT.
This code was generated from a template.

Manual changes to this file may cause unexpected behavior in your application.
Manual changes to this file will be overwritten if the code is regenerated.

Generate info: {{ .AppInfo }}

Code generated by projectStarter generator. DO NOT EDIT file before this message.
Generate info: {{ .AppInfo }}

And everything works fine.

If you need you can add your code after this message

The code that the user wrote after the disclaimer.`
*/
// fmt.Println(" -296 - cheking code before the disclaimer")
